version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1 # Menggunakan orb resmi untuk kemudahan

jobs:
  # Job baru untuk pengecekan Dockerfile
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest-debian
    steps:
      - checkout
      - run:
          name: Run Hadolint
          command: hadolint Dockerfile

  # Job baru untuk unit test aplikasi Go
  test-app:
    docker:
      - image: cimg/go:1.21 # Sesuaikan versi Go
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build_app_karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to GHCR
          command: | 
            echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_USERNAME}" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            IMAGE_TAG="ghcr.io/$GITHUB_USERNAME/karsajobs:latest"
            docker build -t $IMAGE_TAG .
            docker push $IMAGE_TAG
